CREATE TABLE IF NOT EXISTS empleados (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    email  VARCHAR(200) NOT NULL
) ENGINE=InnoDB;
